// Code generated by MockGen. DO NOT EDIT.
// Source: substate_provider.go
//
// Generated by this command:
//
//	mockgen -source substate_provider.go -destination substate_provider_mocks.go -package executor
//
// Package executor is a generated GoMock package.
package executor
