// Code generated by MockGen. DO NOT EDIT.
// Source: state_hash.go

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockStateHashProvider is a mock of StateHashProvider interface.
type MockStateHashProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStateHashProviderMockRecorder
}

// MockStateHashProviderMockRecorder is the mock recorder for MockStateHashProvider.
type MockStateHashProviderMockRecorder struct {
	mock *MockStateHashProvider
}

// NewMockStateHashProvider creates a new mock instance.
func NewMockStateHashProvider(ctrl *gomock.Controller) *MockStateHashProvider {
	mock := &MockStateHashProvider{ctrl: ctrl}
	mock.recorder = &MockStateHashProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateHashProvider) EXPECT() *MockStateHashProviderMockRecorder {
	return m.recorder
}

// GetStateHash mocks base method.
func (m *MockStateHashProvider) GetStateHash(blockNumber int) (common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateHash", blockNumber)
	ret0, _ := ret[0].(common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateHash indicates an expected call of GetStateHash.
func (mr *MockStateHashProviderMockRecorder) GetStateHash(blockNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateHash", reflect.TypeOf((*MockStateHashProvider)(nil).GetStateHash), blockNumber)
}
