name: CI-OSX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    env:
      TEST_TMPDIR: "/Users/runner/.cache/bazel"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
         path: "/Users/runner/.cache/bazel"
         key: bazel-osx

      - name: Build
        run: make

      - name: Test
        run: go test -v ./...

